
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13013618
     no. of nonzeroes in the factor l        =       208915834
     ratio of nonzeroes in factor (min/max)  =          0.7130
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6897
     maximum size of a front matrix          =        23787753
     maximum size of a front trapezoid       =        17077137
     no. of floating point ops for factor    =      5.2881D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5137
     ratio of allocated memory (max/min)     =          1.3515
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.082174
     time (cpu & wall) for ordering          =        0.750000        0.755356
     time (cpu & wall) for other matrix prep =        0.109375        0.114247
     time (cpu & wall) for value input       =        0.203125        0.196362
     time (cpu & wall) for matrix distrib.   =        0.546875        0.541448
     time (cpu & wall) for numeric factor    =       11.968750       11.985277
     computational rate (gflops) for factor  =       44.182968       44.122044
     time (cpu & wall) for numeric solve     =        0.093750        0.099101
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        353842.        3. MB
                95-   1        360448.        3. MB        341163.        3. MB
                95-   2        360448.        3. MB        331745.        3. MB
                95-   3        360448.        3. MB        344538.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371288.       10. MB


  Solver Memory allocated on core    0       =      810.660 MB
  Solver Memory allocated on core    1       =      599.820 MB
  Solver Memory allocated on core    2       =      743.207 MB
  Solver Memory allocated on core    3       =      604.805 MB
  Total Solver Memory allocated by all cores =     2758.492 MB





  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13013618
     no. of nonzeroes in the factor l        =       208915834
     ratio of nonzeroes in factor (min/max)  =          0.7130
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6897
     maximum size of a front matrix          =        23787753
     maximum size of a front trapezoid       =        17077137
     no. of floating point ops for factor    =      5.2881D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5137
     ratio of allocated memory (max/min)     =          1.3515
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.203125        0.206498
     time (cpu & wall) for matrix distrib.   =        0.468750        0.475793
     time (cpu & wall) for numeric factor    =       12.109375       12.147514
     computational rate (gflops) for factor  =       43.669876       43.532769
     time (cpu & wall) for numeric solve     =        0.109375        0.104309
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        353842.        3. MB
                95-   1        360448.        3. MB        341163.        3. MB
                95-   2        360448.        3. MB        331745.        3. MB
                95-   3        360448.        3. MB        344538.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371288.       10. MB


  Solver Memory allocated on core    0       =      810.660 MB
  Solver Memory allocated on core    1       =      599.820 MB
  Solver Memory allocated on core    2       =      743.207 MB
  Solver Memory allocated on core    3       =      604.805 MB
  Total Solver Memory allocated by all cores =     2758.492 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13013618
     no. of nonzeroes in the factor l        =       208915834
     ratio of nonzeroes in factor (min/max)  =          0.7130
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6897
     maximum size of a front matrix          =        23787753
     maximum size of a front trapezoid       =        17077137
     no. of floating point ops for factor    =      5.2881D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5137
     ratio of allocated memory (max/min)     =          1.3515
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.228642
     time (cpu & wall) for matrix distrib.   =        0.515625        0.515993
     time (cpu & wall) for numeric factor    =       11.843750       11.845562
     computational rate (gflops) for factor  =       44.649279       44.642450
     time (cpu & wall) for numeric solve     =        0.109375        0.103998
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        353842.        3. MB
                95-   1        360448.        3. MB        341163.        3. MB
                95-   2        360448.        3. MB        331745.        3. MB
                95-   3        360448.        3. MB        344538.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371288.       10. MB


  Solver Memory allocated on core    0       =      810.660 MB
  Solver Memory allocated on core    1       =      599.820 MB
  Solver Memory allocated on core    2       =      743.207 MB
  Solver Memory allocated on core    3       =      604.805 MB
  Total Solver Memory allocated by all cores =     2758.492 MB





  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13013618
     no. of nonzeroes in the factor l        =       208915834
     ratio of nonzeroes in factor (min/max)  =          0.7130
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6897
     maximum size of a front matrix          =        23787753
     maximum size of a front trapezoid       =        17077137
     no. of floating point ops for factor    =      5.2881D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5137
     ratio of allocated memory (max/min)     =          1.3515
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.265625        0.262103
     time (cpu & wall) for matrix distrib.   =        0.562500        0.563386
     time (cpu & wall) for numeric factor    =       11.593750       11.603294
     computational rate (gflops) for factor  =       45.612067       45.574551
     time (cpu & wall) for numeric solve     =        0.093750        0.098297
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        353842.        3. MB
                95-   1        360448.        3. MB        341163.        3. MB
                95-   2        360448.        3. MB        331745.        3. MB
                95-   3        360448.        3. MB        344538.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371288.       10. MB


  Solver Memory allocated on core    0       =      810.660 MB
  Solver Memory allocated on core    1       =      599.820 MB
  Solver Memory allocated on core    2       =      743.207 MB
  Solver Memory allocated on core    3       =      604.805 MB
  Total Solver Memory allocated by all cores =     2758.492 MB





  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13013618
     no. of nonzeroes in the factor l        =       208915834
     ratio of nonzeroes in factor (min/max)  =          0.7130
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6897
     maximum size of a front matrix          =        23787753
     maximum size of a front trapezoid       =        17077137
     no. of floating point ops for factor    =      5.2881D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5137
     ratio of allocated memory (max/min)     =          1.3515
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.240754
     time (cpu & wall) for matrix distrib.   =        0.484375        0.484285
     time (cpu & wall) for numeric factor    =       11.515625       11.521299
     computational rate (gflops) for factor  =       45.921511       45.898898
     time (cpu & wall) for numeric solve     =        0.093750        0.105032
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        353842.        3. MB
                95-   1        360448.        3. MB        341163.        3. MB
                95-   2        360448.        3. MB        331745.        3. MB
                95-   3        360448.        3. MB        344538.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371288.       10. MB


  Solver Memory allocated on core    0       =      810.660 MB
  Solver Memory allocated on core    1       =      599.820 MB
  Solver Memory allocated on core    2       =      743.207 MB
  Solver Memory allocated on core    3       =      604.805 MB
  Total Solver Memory allocated by all cores =     2758.492 MB





  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13013618
     no. of nonzeroes in the factor l        =       208915834
     ratio of nonzeroes in factor (min/max)  =          0.7130
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6897
     maximum size of a front matrix          =        23787753
     maximum size of a front trapezoid       =        17077137
     no. of floating point ops for factor    =      5.2881D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5137
     ratio of allocated memory (max/min)     =          1.3515
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.218750        0.222025
     time (cpu & wall) for matrix distrib.   =        0.515625        0.516436
     time (cpu & wall) for numeric factor    =       11.718750       11.742021
     computational rate (gflops) for factor  =       45.125538       45.036106
     time (cpu & wall) for numeric solve     =        0.109375        0.104216
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        353842.        3. MB
                95-   1        360448.        3. MB        341163.        3. MB
                95-   2        360448.        3. MB        331745.        3. MB
                95-   3        360448.        3. MB        344538.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371288.       10. MB


  Solver Memory allocated on core    0       =      810.660 MB
  Solver Memory allocated on core    1       =      599.820 MB
  Solver Memory allocated on core    2       =      743.207 MB
  Solver Memory allocated on core    3       =      604.805 MB
  Total Solver Memory allocated by all cores =     2758.492 MB





  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13013618
     no. of nonzeroes in the factor l        =       208915834
     ratio of nonzeroes in factor (min/max)  =          0.7130
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6897
     maximum size of a front matrix          =        23787753
     maximum size of a front trapezoid       =        17077137
     no. of floating point ops for factor    =      5.2881D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5137
     ratio of allocated memory (max/min)     =          1.3515
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.230766
     time (cpu & wall) for matrix distrib.   =        0.546875        0.549246
     time (cpu & wall) for numeric factor    =       11.984375       12.002761
     computational rate (gflops) for factor  =       44.125364       44.057771
     time (cpu & wall) for numeric solve     =        0.093750        0.101377
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        353842.        3. MB
                95-   1        360448.        3. MB        341163.        3. MB
                95-   2        360448.        3. MB        331745.        3. MB
                95-   3        360448.        3. MB        344538.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371288.       10. MB


  Solver Memory allocated on core    0       =      810.660 MB
  Solver Memory allocated on core    1       =      599.820 MB
  Solver Memory allocated on core    2       =      743.207 MB
  Solver Memory allocated on core    3       =      604.805 MB
  Total Solver Memory allocated by all cores =     2758.492 MB





  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13013618
     no. of nonzeroes in the factor l        =       208915834
     ratio of nonzeroes in factor (min/max)  =          0.7130
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6897
     maximum size of a front matrix          =        23787753
     maximum size of a front trapezoid       =        17077137
     no. of floating point ops for factor    =      5.2881D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5137
     ratio of allocated memory (max/min)     =          1.3515
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.218750        0.220070
     time (cpu & wall) for matrix distrib.   =        0.531250        0.528855
     time (cpu & wall) for numeric factor    =       11.625000       11.648692
     computational rate (gflops) for factor  =       45.489454       45.396934
     time (cpu & wall) for numeric solve     =        0.093750        0.106528
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        353842.        3. MB
                95-   1        360448.        3. MB        341163.        3. MB
                95-   2        360448.        3. MB        331745.        3. MB
                95-   3        360448.        3. MB        344538.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371288.       10. MB


  Solver Memory allocated on core    0       =      810.660 MB
  Solver Memory allocated on core    1       =      599.820 MB
  Solver Memory allocated on core    2       =      743.207 MB
  Solver Memory allocated on core    3       =      604.805 MB
  Total Solver Memory allocated by all cores =     2758.492 MB





  Performance statistics for DSP solver: icalls =      9

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13013618
     no. of nonzeroes in the factor l        =       208915834
     ratio of nonzeroes in factor (min/max)  =          0.7130
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6897
     maximum size of a front matrix          =        23787753
     maximum size of a front trapezoid       =        17077137
     no. of floating point ops for factor    =      5.2881D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5137
     ratio of allocated memory (max/min)     =          1.3515
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.218750        0.225337
     time (cpu & wall) for matrix distrib.   =        0.500000        0.494605
     time (cpu & wall) for numeric factor    =       11.546875       11.565881
     computational rate (gflops) for factor  =       45.797231       45.721973
     time (cpu & wall) for numeric solve     =        0.109375        0.106252
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        353842.        3. MB
                95-   1        360448.        3. MB        341163.        3. MB
                95-   2        360448.        3. MB        331745.        3. MB
                95-   3        360448.        3. MB        344538.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371288.       10. MB


  Solver Memory allocated on core    0       =      810.660 MB
  Solver Memory allocated on core    1       =      599.820 MB
  Solver Memory allocated on core    2       =      743.207 MB
  Solver Memory allocated on core    3       =      604.805 MB
  Total Solver Memory allocated by all cores =     2758.492 MB





  Performance statistics for DSP solver: icalls =     10

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13013618
     no. of nonzeroes in the factor l        =       208915834
     ratio of nonzeroes in factor (min/max)  =          0.7130
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6897
     maximum size of a front matrix          =        23787753
     maximum size of a front trapezoid       =        17077137
     no. of floating point ops for factor    =      5.2881D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5137
     ratio of allocated memory (max/min)     =          1.3515
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.235549
     time (cpu & wall) for matrix distrib.   =        0.515625        0.518601
     time (cpu & wall) for numeric factor    =       11.796875       11.788135
     computational rate (gflops) for factor  =       44.826694       44.859928
     time (cpu & wall) for numeric solve     =        0.093750        0.096952
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        353842.        3. MB
                95-   1        360448.        3. MB        341163.        3. MB
                95-   2        360448.        3. MB        331745.        3. MB
                95-   3        360448.        3. MB        344538.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371288.       10. MB


  Solver Memory allocated on core    0       =      810.660 MB
  Solver Memory allocated on core    1       =      599.820 MB
  Solver Memory allocated on core    2       =      743.207 MB
  Solver Memory allocated on core    3       =      604.805 MB
  Total Solver Memory allocated by all cores =     2758.492 MB





  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13013618
     no. of nonzeroes in the factor l        =       208915834
     ratio of nonzeroes in factor (min/max)  =          0.7130
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6897
     maximum size of a front matrix          =        23787753
     maximum size of a front trapezoid       =        17077137
     no. of floating point ops for factor    =      5.2881D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5137
     ratio of allocated memory (max/min)     =          1.3515
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.232969
     time (cpu & wall) for matrix distrib.   =        0.562500        0.551551
     time (cpu & wall) for numeric factor    =       11.765625       11.782510
     computational rate (gflops) for factor  =       44.945755       44.881346
     time (cpu & wall) for numeric solve     =        0.093750        0.102533
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        353842.        3. MB
                95-   1        360448.        3. MB        341163.        3. MB
                95-   2        360448.        3. MB        331745.        3. MB
                95-   3        360448.        3. MB        344538.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371288.       10. MB


  Solver Memory allocated on core    0       =      810.660 MB
  Solver Memory allocated on core    1       =      599.820 MB
  Solver Memory allocated on core    2       =      743.207 MB
  Solver Memory allocated on core    3       =      604.805 MB
  Total Solver Memory allocated by all cores =     2758.492 MB





  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13013618
     no. of nonzeroes in the factor l        =       208915834
     ratio of nonzeroes in factor (min/max)  =          0.7130
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6897
     maximum size of a front matrix          =        23787753
     maximum size of a front trapezoid       =        17077137
     no. of floating point ops for factor    =      5.2881D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5137
     ratio of allocated memory (max/min)     =          1.3515
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.229315
     time (cpu & wall) for matrix distrib.   =        0.515625        0.515897
     time (cpu & wall) for numeric factor    =       11.953125       11.942139
     computational rate (gflops) for factor  =       44.240724       44.281421
     time (cpu & wall) for numeric solve     =        0.109375        0.106700
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        353842.        3. MB
                95-   1        360448.        3. MB        341163.        3. MB
                95-   2        360448.        3. MB        331745.        3. MB
                95-   3        360448.        3. MB        344538.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371288.       10. MB


  Solver Memory allocated on core    0       =      810.660 MB
  Solver Memory allocated on core    1       =      599.820 MB
  Solver Memory allocated on core    2       =      743.207 MB
  Solver Memory allocated on core    3       =      604.805 MB
  Total Solver Memory allocated by all cores =     2758.492 MB





  Performance statistics for DSP solver: icalls =     13

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13040044
     no. of nonzeroes in the factor l        =       207601130
     ratio of nonzeroes in factor (min/max)  =          0.8529
     number of super nodes                   =            2820
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1004D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6554
     ratio of allocated memory (max/min)     =          1.2208
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.187500        0.190491
     time (cpu & wall) for ordering          =        0.734375        0.745263
     time (cpu & wall) for other matrix prep =        0.093750        0.090735
     time (cpu & wall) for value input       =        0.421875        0.425148
     time (cpu & wall) for matrix distrib.   =        1.031250        1.030194
     time (cpu & wall) for numeric factor    =        9.484375        9.507029
     computational rate (gflops) for factor  =       53.776787       53.648646
     time (cpu & wall) for numeric solve     =        0.109375        0.096419
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        325336.        2. MB
                95-   1        393216.        3. MB        372223.        3. MB
                95-   2        360448.        3. MB        348595.        3. MB
                95-   3        360448.        3. MB        330759.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1376913.       11. MB


  Solver Memory allocated on core    0       =      696.258 MB
  Solver Memory allocated on core    1       =      682.144 MB
  Solver Memory allocated on core    2       =      743.826 MB
  Solver Memory allocated on core    3       =      609.297 MB
  Total Solver Memory allocated by all cores =     2731.526 MB





  Performance statistics for DSP solver: icalls =     14

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13042078
     no. of nonzeroes in the factor l        =       208465763
     ratio of nonzeroes in factor (min/max)  =          0.8067
     number of super nodes                   =            2791
     maximum order of a front matrix         =            6798
     maximum size of a front matrix          =        23109801
     maximum size of a front trapezoid       =        17104956
     no. of floating point ops for factor    =      5.1940D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5868
     ratio of allocated memory (max/min)     =          1.2282
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.090612
     time (cpu & wall) for ordering          =        0.718750        0.704653
     time (cpu & wall) for other matrix prep =        0.093750        0.098340
     time (cpu & wall) for value input       =        0.250000        0.239160
     time (cpu & wall) for matrix distrib.   =        0.531250        0.519112
     time (cpu & wall) for numeric factor    =       11.000000       11.025259
     computational rate (gflops) for factor  =       47.218435       47.110258
     time (cpu & wall) for numeric solve     =        0.125000        0.112239
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        347295.        3. MB
                95-   1        360448.        3. MB        348845.        3. MB
                95-   2        327680.        2. MB        323639.        2. MB
                95-   3        360448.        3. MB        351478.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1371257.       10. MB


  Solver Memory allocated on core    0       =      780.385 MB
  Solver Memory allocated on core    1       =      635.394 MB
  Solver Memory allocated on core    2       =      687.907 MB
  Solver Memory allocated on core    3       =      645.292 MB
  Total Solver Memory allocated by all cores =     2748.979 MB





  Performance statistics for DSP solver: icalls =     15

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13040584
     no. of nonzeroes in the factor l        =       208303449
     ratio of nonzeroes in factor (min/max)  =          0.8080
     number of super nodes                   =            2794
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1534D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5951
     ratio of allocated memory (max/min)     =          1.2757
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.078125        0.088529
     time (cpu & wall) for ordering          =        0.718750        0.735573
     time (cpu & wall) for other matrix prep =        0.093750        0.092140
     time (cpu & wall) for value input       =        0.218750        0.227843
     time (cpu & wall) for matrix distrib.   =        0.515625        0.513572
     time (cpu & wall) for numeric factor    =        9.843750        9.856832
     computational rate (gflops) for factor  =       52.352324       52.282839
     time (cpu & wall) for numeric solve     =        0.093750        0.102138
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        321982.        2. MB
                95-   1        393216.        3. MB        376067.        3. MB
                95-   2        360448.        3. MB        344669.        3. MB
                95-   3        360448.        3. MB        328452.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371170.       10. MB


  Solver Memory allocated on core    0       =      689.577 MB
  Solver Memory allocated on core    1       =      683.560 MB
  Solver Memory allocated on core    2       =      766.710 MB
  Solver Memory allocated on core    3       =      601.001 MB
  Total Solver Memory allocated by all cores =     2740.848 MB





  Performance statistics for DSP solver: icalls =     16

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13040584
     no. of nonzeroes in the factor l        =       208303449
     ratio of nonzeroes in factor (min/max)  =          0.8080
     number of super nodes                   =            2794
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1534D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5951
     ratio of allocated memory (max/min)     =          1.2757
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.109375        0.104810
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.218750        0.212493
     time (cpu & wall) for matrix distrib.   =        0.531250        0.533700
     time (cpu & wall) for numeric factor    =        9.671875        9.668861
     computational rate (gflops) for factor  =       53.282656       53.299265
     time (cpu & wall) for numeric solve     =        0.109375        0.103726
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        321982.        2. MB
                95-   1        393216.        3. MB        376067.        3. MB
                95-   2        360448.        3. MB        344669.        3. MB
                95-   3        360448.        3. MB        328452.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1371170.       10. MB


  Solver Memory allocated on core    0       =      689.577 MB
  Solver Memory allocated on core    1       =      683.560 MB
  Solver Memory allocated on core    2       =      766.710 MB
  Solver Memory allocated on core    3       =      601.001 MB
  Total Solver Memory allocated by all cores =     2740.849 MB





  Performance statistics for DSP solver: icalls =     17

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041448
     no. of nonzeroes in the factor l        =       209988302
     ratio of nonzeroes in factor (min/max)  =          0.9550
     number of super nodes                   =            2815
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1621D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.7299
     ratio of allocated memory (max/min)     =          1.1047
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.171875        0.186222
     time (cpu & wall) for ordering          =        0.703125        0.705486
     time (cpu & wall) for other matrix prep =        0.093750        0.093744
     time (cpu & wall) for value input       =        0.484375        0.494130
     time (cpu & wall) for matrix distrib.   =        1.046875        1.050250
     time (cpu & wall) for numeric factor    =        9.687500        9.704272
     computational rate (gflops) for factor  =       53.286465       53.194372
     time (cpu & wall) for numeric solve     =        0.093750        0.101583
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        322957.        2. MB
                95-   1        393216.        3. MB        373462.        3. MB
                95-   2        360448.        3. MB        328901.        3. MB
                95-   3        360448.        3. MB        351017.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1376337.       11. MB


  Solver Memory allocated on core    0       =      693.229 MB
  Solver Memory allocated on core    1       =      680.457 MB
  Solver Memory allocated on core    2       =      718.475 MB
  Solver Memory allocated on core    3       =      650.405 MB
  Total Solver Memory allocated by all cores =     2742.566 MB





  Performance statistics for DSP solver: icalls =     18

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041448
     no. of nonzeroes in the factor l        =       209988302
     ratio of nonzeroes in factor (min/max)  =          0.9550
     number of super nodes                   =            2815
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1621D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.7299
     ratio of allocated memory (max/min)     =          1.1047
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.250000        0.251076
     time (cpu & wall) for matrix distrib.   =        0.515625        0.517285
     time (cpu & wall) for numeric factor    =        9.468750        9.442265
     computational rate (gflops) for factor  =       54.517505       54.670426
     time (cpu & wall) for numeric solve     =        0.093750        0.095471
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        322957.        2. MB
                95-   1        393216.        3. MB        373462.        3. MB
                95-   2        360448.        3. MB        328901.        3. MB
                95-   3        360448.        3. MB        351017.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1376337.       11. MB


  Solver Memory allocated on core    0       =      693.229 MB
  Solver Memory allocated on core    1       =      680.457 MB
  Solver Memory allocated on core    2       =      718.475 MB
  Solver Memory allocated on core    3       =      650.405 MB
  Total Solver Memory allocated by all cores =     2742.566 MB





  Performance statistics for DSP solver: icalls =     19

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041448
     no. of nonzeroes in the factor l        =       209988302
     ratio of nonzeroes in factor (min/max)  =          0.9550
     number of super nodes                   =            2815
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1621D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.7299
     ratio of allocated memory (max/min)     =          1.1047
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.244570
     time (cpu & wall) for matrix distrib.   =        0.531250        0.536997
     time (cpu & wall) for numeric factor    =        9.171875        9.174705
     computational rate (gflops) for factor  =       56.282127       56.264767
     time (cpu & wall) for numeric solve     =        0.093750        0.096111
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        322957.        2. MB
                95-   1        393216.        3. MB        373462.        3. MB
                95-   2        360448.        3. MB        328901.        3. MB
                95-   3        360448.        3. MB        351017.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1376337.       11. MB


  Solver Memory allocated on core    0       =      693.229 MB
  Solver Memory allocated on core    1       =      680.457 MB
  Solver Memory allocated on core    2       =      718.475 MB
  Solver Memory allocated on core    3       =      650.405 MB
  Total Solver Memory allocated by all cores =     2742.566 MB





  Performance statistics for DSP solver: icalls =     20

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041448
     no. of nonzeroes in the factor l        =       209988302
     ratio of nonzeroes in factor (min/max)  =          0.9550
     number of super nodes                   =            2815
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1621D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.7299
     ratio of allocated memory (max/min)     =          1.1047
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.250000        0.259222
     time (cpu & wall) for matrix distrib.   =        0.531250        0.535167
     time (cpu & wall) for numeric factor    =        9.390625        9.431435
     computational rate (gflops) for factor  =       54.971062       54.733202
     time (cpu & wall) for numeric solve     =        0.109375        0.106635
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        322957.        2. MB
                95-   1        393216.        3. MB        373462.        3. MB
                95-   2        360448.        3. MB        328901.        3. MB
                95-   3        360448.        3. MB        351017.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1376337.       11. MB


  Solver Memory allocated on core    0       =      693.229 MB
  Solver Memory allocated on core    1       =      680.457 MB
  Solver Memory allocated on core    2       =      718.475 MB
  Solver Memory allocated on core    3       =      650.405 MB
  Total Solver Memory allocated by all cores =     2742.566 MB





  Performance statistics for DSP solver: icalls =     21

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041448
     no. of nonzeroes in the factor l        =       209988302
     ratio of nonzeroes in factor (min/max)  =          0.9550
     number of super nodes                   =            2815
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1621D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.7299
     ratio of allocated memory (max/min)     =          1.1047
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.241663
     time (cpu & wall) for matrix distrib.   =        0.500000        0.500631
     time (cpu & wall) for numeric factor    =        9.468750        9.494582
     computational rate (gflops) for factor  =       54.517505       54.369179
     time (cpu & wall) for numeric solve     =        0.093750        0.103518
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        322957.        2. MB
                95-   1        393216.        3. MB        373462.        3. MB
                95-   2        360448.        3. MB        328901.        3. MB
                95-   3        360448.        3. MB        351017.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1376337.       11. MB


  Solver Memory allocated on core    0       =      693.229 MB
  Solver Memory allocated on core    1       =      680.457 MB
  Solver Memory allocated on core    2       =      718.475 MB
  Solver Memory allocated on core    3       =      650.405 MB
  Total Solver Memory allocated by all cores =     2742.566 MB





  Performance statistics for DSP solver: icalls =     22

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041448
     no. of nonzeroes in the factor l        =       209988302
     ratio of nonzeroes in factor (min/max)  =          0.9550
     number of super nodes                   =            2815
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1621D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.7299
     ratio of allocated memory (max/min)     =          1.1047
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.265625        0.259845
     time (cpu & wall) for matrix distrib.   =        0.546875        0.551953
     time (cpu & wall) for numeric factor    =        9.015625        9.053008
     computational rate (gflops) for factor  =       57.257553       57.021116
     time (cpu & wall) for numeric solve     =        0.093750        0.100336
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        322957.        2. MB
                95-   1        393216.        3. MB        373462.        3. MB
                95-   2        360448.        3. MB        328901.        3. MB
                95-   3        360448.        3. MB        351017.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1376337.       11. MB


  Solver Memory allocated on core    0       =      693.229 MB
  Solver Memory allocated on core    1       =      680.457 MB
  Solver Memory allocated on core    2       =      718.475 MB
  Solver Memory allocated on core    3       =      650.405 MB
  Total Solver Memory allocated by all cores =     2742.566 MB





  Performance statistics for DSP solver: icalls =     23

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041448
     no. of nonzeroes in the factor l        =       209988302
     ratio of nonzeroes in factor (min/max)  =          0.9550
     number of super nodes                   =            2815
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1621D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.7299
     ratio of allocated memory (max/min)     =          1.1047
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.078125        0.078520
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.250000        0.245948
     time (cpu & wall) for matrix distrib.   =        0.562500        0.555035
     time (cpu & wall) for numeric factor    =        9.328125        9.338848
     computational rate (gflops) for factor  =       55.339377       55.275837
     time (cpu & wall) for numeric solve     =        0.078125        0.101756
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        322957.        2. MB
                95-   1        393216.        3. MB        373462.        3. MB
                95-   2        360448.        3. MB        328901.        3. MB
                95-   3        360448.        3. MB        351017.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1376337.       11. MB


  Solver Memory allocated on core    0       =      693.229 MB
  Solver Memory allocated on core    1       =      680.458 MB
  Solver Memory allocated on core    2       =      718.475 MB
  Solver Memory allocated on core    3       =      650.405 MB
  Total Solver Memory allocated by all cores =     2742.567 MB





  Performance statistics for DSP solver: icalls =     24

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041448
     no. of nonzeroes in the factor l        =       209988302
     ratio of nonzeroes in factor (min/max)  =          0.9550
     number of super nodes                   =            2815
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1621D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.7299
     ratio of allocated memory (max/min)     =          1.1047
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.232812
     time (cpu & wall) for matrix distrib.   =        0.531250        0.531223
     time (cpu & wall) for numeric factor    =        9.312500        9.311763
     computational rate (gflops) for factor  =       55.432229       55.436614
     time (cpu & wall) for numeric solve     =        0.093750        0.098864
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        322957.        2. MB
                95-   1        393216.        3. MB        373462.        3. MB
                95-   2        360448.        3. MB        328901.        3. MB
                95-   3        360448.        3. MB        351017.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1376337.       11. MB


  Solver Memory allocated on core    0       =      693.229 MB
  Solver Memory allocated on core    1       =      680.458 MB
  Solver Memory allocated on core    2       =      718.475 MB
  Solver Memory allocated on core    3       =      650.405 MB
  Total Solver Memory allocated by all cores =     2742.567 MB





  Performance statistics for DSP solver: icalls =     25

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041448
     no. of nonzeroes in the factor l        =       209988302
     ratio of nonzeroes in factor (min/max)  =          0.9550
     number of super nodes                   =            2815
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1621D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.7299
     ratio of allocated memory (max/min)     =          1.1047
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.250000        0.237169
     time (cpu & wall) for matrix distrib.   =        0.531250        0.525760
     time (cpu & wall) for numeric factor    =        9.156250        9.157107
     computational rate (gflops) for factor  =       56.378171       56.372897
     time (cpu & wall) for numeric solve     =        0.093750        0.094862
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        322957.        2. MB
                95-   1        393216.        3. MB        373462.        3. MB
                95-   2        360448.        3. MB        328901.        3. MB
                95-   3        360448.        3. MB        351017.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1376337.       11. MB


  Solver Memory allocated on core    0       =      693.229 MB
  Solver Memory allocated on core    1       =      680.458 MB
  Solver Memory allocated on core    2       =      718.475 MB
  Solver Memory allocated on core    3       =      650.405 MB
  Total Solver Memory allocated by all cores =     2742.567 MB





  Performance statistics for DSP solver: icalls =     26

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041448
     no. of nonzeroes in the factor l        =       209988302
     ratio of nonzeroes in factor (min/max)  =          0.9550
     number of super nodes                   =            2815
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1621D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.7299
     ratio of allocated memory (max/min)     =          1.1047
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.235689
     time (cpu & wall) for matrix distrib.   =        0.562500        0.559918
     time (cpu & wall) for numeric factor    =        9.343750        9.344975
     computational rate (gflops) for factor  =       55.246837       55.239592
     time (cpu & wall) for numeric solve     =        0.093750        0.101824
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        322957.        2. MB
                95-   1        393216.        3. MB        373462.        3. MB
                95-   2        360448.        3. MB        328901.        3. MB
                95-   3        360448.        3. MB        351017.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1376337.       11. MB


  Solver Memory allocated on core    0       =      693.229 MB
  Solver Memory allocated on core    1       =      680.458 MB
  Solver Memory allocated on core    2       =      718.475 MB
  Solver Memory allocated on core    3       =      650.405 MB
  Total Solver Memory allocated by all cores =     2742.567 MB





  Performance statistics for DSP solver: icalls =     27

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041448
     no. of nonzeroes in the factor l        =       209988302
     ratio of nonzeroes in factor (min/max)  =          0.9550
     number of super nodes                   =            2815
     maximum order of a front matrix         =            6303
     maximum size of a front matrix          =        19867056
     maximum size of a front trapezoid       =        14528778
     no. of floating point ops for factor    =      5.1621D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.7299
     ratio of allocated memory (max/min)     =          1.1047
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.090101
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.231934
     time (cpu & wall) for matrix distrib.   =        0.531250        0.533841
     time (cpu & wall) for numeric factor    =        9.765625        9.769295
     computational rate (gflops) for factor  =       52.860173       52.840317
     time (cpu & wall) for numeric solve     =        0.093750        0.095204
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        327680.        2. MB        322957.        2. MB
                95-   1        393216.        3. MB        373462.        3. MB
                95-   2        360448.        3. MB        328901.        3. MB
                95-   3        360448.        3. MB        351017.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1376337.       11. MB


  Solver Memory allocated on core    0       =      693.229 MB
  Solver Memory allocated on core    1       =      680.458 MB
  Solver Memory allocated on core    2       =      718.475 MB
  Solver Memory allocated on core    3       =      650.405 MB
  Total Solver Memory allocated by all cores =     2742.568 MB





  Performance statistics for DSP solver: icalls =     28

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041760
     no. of nonzeroes in the factor l        =       206550650
     ratio of nonzeroes in factor (min/max)  =          0.8541
     number of super nodes                   =            2795
     maximum order of a front matrix         =            6600
     maximum size of a front matrix          =        21783300
     maximum size of a front trapezoid       =        15778455
     no. of floating point ops for factor    =      5.0437D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6534
     ratio of allocated memory (max/min)     =          1.1712
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.187500        0.184942
     time (cpu & wall) for ordering          =        0.734375        0.731477
     time (cpu & wall) for other matrix prep =        0.093750        0.097155
     time (cpu & wall) for value input       =        0.468750        0.474490
     time (cpu & wall) for matrix distrib.   =        1.046875        1.056984
     time (cpu & wall) for numeric factor    =       10.421875       10.422649
     computational rate (gflops) for factor  =       48.395105       48.391513
     time (cpu & wall) for numeric solve     =        0.093750        0.103049
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        349841.        3. MB
                95-   1        360448.        3. MB        348957.        3. MB
                95-   2        327680.        2. MB        318321.        2. MB
                95-   3        360448.        3. MB        352325.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369444.       10. MB


  Solver Memory allocated on core    0       =      748.429 MB
  Solver Memory allocated on core    1       =      639.051 MB
  Solver Memory allocated on core    2       =      684.436 MB
  Solver Memory allocated on core    3       =      651.247 MB
  Total Solver Memory allocated by all cores =     2723.163 MB





  Performance statistics for DSP solver: icalls =     29

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041760
     no. of nonzeroes in the factor l        =       206550650
     ratio of nonzeroes in factor (min/max)  =          0.8541
     number of super nodes                   =            2795
     maximum order of a front matrix         =            6600
     maximum size of a front matrix          =        21783300
     maximum size of a front trapezoid       =        15778455
     no. of floating point ops for factor    =      5.0437D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6534
     ratio of allocated memory (max/min)     =          1.1711
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.089137
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.232357
     time (cpu & wall) for matrix distrib.   =        0.500000        0.505518
     time (cpu & wall) for numeric factor    =       10.375000       10.361340
     computational rate (gflops) for factor  =       48.613758       48.677846
     time (cpu & wall) for numeric solve     =        0.109375        0.101784
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        349841.        3. MB
                95-   1        360448.        3. MB        348957.        3. MB
                95-   2        327680.        2. MB        318321.        2. MB
                95-   3        360448.        3. MB        352325.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369444.       10. MB


  Solver Memory allocated on core    0       =      748.429 MB
  Solver Memory allocated on core    1       =      639.056 MB
  Solver Memory allocated on core    2       =      684.436 MB
  Solver Memory allocated on core    3       =      651.247 MB
  Total Solver Memory allocated by all cores =     2723.168 MB





  Performance statistics for DSP solver: icalls =     30

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13042084
     no. of nonzeroes in the factor l        =       209259374
     ratio of nonzeroes in factor (min/max)  =          0.7825
     number of super nodes                   =            2793
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1773D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5690
     ratio of allocated memory (max/min)     =          1.2518
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.078125        0.078121
     time (cpu & wall) for ordering          =        0.765625        0.767186
     time (cpu & wall) for other matrix prep =        0.109375        0.107189
     time (cpu & wall) for value input       =        0.234375        0.234425
     time (cpu & wall) for matrix distrib.   =        0.500000        0.498752
     time (cpu & wall) for numeric factor    =       11.125000       11.138963
     computational rate (gflops) for factor  =       46.537395       46.479061
     time (cpu & wall) for numeric solve     =        0.109375        0.105747
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        351873.        3. MB
                95-   1        360448.        3. MB        343147.        3. MB
                95-   2        327680.        2. MB        325927.        2. MB
                95-   3        360448.        3. MB        352273.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1373220.       10. MB


  Solver Memory allocated on core    0       =      777.299 MB
  Solver Memory allocated on core    1       =      620.941 MB
  Solver Memory allocated on core    2       =      693.670 MB
  Solver Memory allocated on core    3       =      651.408 MB
  Total Solver Memory allocated by all cores =     2743.318 MB





  Performance statistics for DSP solver: icalls =     31

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13042084
     no. of nonzeroes in the factor l        =       209259374
     ratio of nonzeroes in factor (min/max)  =          0.7825
     number of super nodes                   =            2793
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1773D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5690
     ratio of allocated memory (max/min)     =          1.2518
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.244820
     time (cpu & wall) for matrix distrib.   =        0.515625        0.529168
     time (cpu & wall) for numeric factor    =       11.078125       11.082387
     computational rate (gflops) for factor  =       46.734309       46.716335
     time (cpu & wall) for numeric solve     =        0.093750        0.095935
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        351873.        3. MB
                95-   1        360448.        3. MB        343147.        3. MB
                95-   2        327680.        2. MB        325927.        2. MB
                95-   3        360448.        3. MB        352273.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1373220.       10. MB


  Solver Memory allocated on core    0       =      777.299 MB
  Solver Memory allocated on core    1       =      620.941 MB
  Solver Memory allocated on core    2       =      693.670 MB
  Solver Memory allocated on core    3       =      651.408 MB
  Total Solver Memory allocated by all cores =     2743.318 MB





  Performance statistics for DSP solver: icalls =     32

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13042084
     no. of nonzeroes in the factor l        =       209259374
     ratio of nonzeroes in factor (min/max)  =          0.7825
     number of super nodes                   =            2793
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1773D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5690
     ratio of allocated memory (max/min)     =          1.2518
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.237502
     time (cpu & wall) for matrix distrib.   =        0.531250        0.526656
     time (cpu & wall) for numeric factor    =       11.125000       11.144848
     computational rate (gflops) for factor  =       46.537395       46.454516
     time (cpu & wall) for numeric solve     =        0.093750        0.097987
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        351873.        3. MB
                95-   1        360448.        3. MB        343147.        3. MB
                95-   2        327680.        2. MB        325927.        2. MB
                95-   3        360448.        3. MB        352273.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1373220.       10. MB


  Solver Memory allocated on core    0       =      777.299 MB
  Solver Memory allocated on core    1       =      620.941 MB
  Solver Memory allocated on core    2       =      693.670 MB
  Solver Memory allocated on core    3       =      651.408 MB
  Total Solver Memory allocated by all cores =     2743.318 MB





  Performance statistics for DSP solver: icalls =     33

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13042084
     no. of nonzeroes in the factor l        =       209259374
     ratio of nonzeroes in factor (min/max)  =          0.7825
     number of super nodes                   =            2793
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1773D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5690
     ratio of allocated memory (max/min)     =          1.2518
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.092526
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.250000        0.252278
     time (cpu & wall) for matrix distrib.   =        0.531250        0.523891
     time (cpu & wall) for numeric factor    =       10.937500       10.938860
     computational rate (gflops) for factor  =       47.335179       47.329292
     time (cpu & wall) for numeric solve     =        0.109375        0.101446
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        351873.        3. MB
                95-   1        360448.        3. MB        343147.        3. MB
                95-   2        327680.        2. MB        325927.        2. MB
                95-   3        360448.        3. MB        352273.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1373220.       10. MB


  Solver Memory allocated on core    0       =      777.299 MB
  Solver Memory allocated on core    1       =      620.939 MB
  Solver Memory allocated on core    2       =      693.670 MB
  Solver Memory allocated on core    3       =      651.408 MB
  Total Solver Memory allocated by all cores =     2743.316 MB





  Performance statistics for DSP solver: icalls =     34

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13042912
     no. of nonzeroes in the factor l        =       206637577
     ratio of nonzeroes in factor (min/max)  =          0.9577
     number of super nodes                   =            2845
     maximum order of a front matrix         =            6204
     maximum size of a front matrix          =        19247910
     maximum size of a front trapezoid       =        13909632
     no. of floating point ops for factor    =      4.9568D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8282
     ratio of allocated memory (max/min)     =          1.0610
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.203125        0.196899
     time (cpu & wall) for ordering          =        0.734375        0.724894
     time (cpu & wall) for other matrix prep =        0.093750        0.101264
     time (cpu & wall) for value input       =        0.484375        0.482240
     time (cpu & wall) for matrix distrib.   =        1.109375        1.087809
     time (cpu & wall) for numeric factor    =        9.328125        9.330731
     computational rate (gflops) for factor  =       53.138556       53.123714
     time (cpu & wall) for numeric solve     =        0.109375        0.110478
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        328724.        3. MB
                95-   1        393216.        3. MB        372309.        3. MB
                95-   2        327680.        2. MB        324793.        2. MB
                95-   3        360448.        3. MB        354203.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1380029.       11. MB


  Solver Memory allocated on core    0       =      680.288 MB
  Solver Memory allocated on core    1       =      689.503 MB
  Solver Memory allocated on core    2       =      680.207 MB
  Solver Memory allocated on core    3       =      649.872 MB
  Total Solver Memory allocated by all cores =     2699.870 MB





  Performance statistics for DSP solver: icalls =     35

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13042912
     no. of nonzeroes in the factor l        =       206637577
     ratio of nonzeroes in factor (min/max)  =          0.9577
     number of super nodes                   =            2845
     maximum order of a front matrix         =            6204
     maximum size of a front matrix          =        19247910
     maximum size of a front trapezoid       =        13909632
     no. of floating point ops for factor    =      4.9568D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8282
     ratio of allocated memory (max/min)     =          1.0610
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.250000        0.245441
     time (cpu & wall) for matrix distrib.   =        0.546875        0.544730
     time (cpu & wall) for numeric factor    =        9.281250        9.286671
     computational rate (gflops) for factor  =       53.406933       53.375758
     time (cpu & wall) for numeric solve     =        0.093750        0.098573
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        328724.        3. MB
                95-   1        393216.        3. MB        372309.        3. MB
                95-   2        327680.        2. MB        324793.        2. MB
                95-   3        360448.        3. MB        354203.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1380029.       11. MB


  Solver Memory allocated on core    0       =      680.288 MB
  Solver Memory allocated on core    1       =      689.503 MB
  Solver Memory allocated on core    2       =      680.207 MB
  Solver Memory allocated on core    3       =      649.872 MB
  Total Solver Memory allocated by all cores =     2699.870 MB





  Performance statistics for DSP solver: icalls =     36

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13042912
     no. of nonzeroes in the factor l        =       206637577
     ratio of nonzeroes in factor (min/max)  =          0.9577
     number of super nodes                   =            2845
     maximum order of a front matrix         =            6204
     maximum size of a front matrix          =        19247910
     maximum size of a front trapezoid       =        13909632
     no. of floating point ops for factor    =      4.9568D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8282
     ratio of allocated memory (max/min)     =          1.0610
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.250000        0.248905
     time (cpu & wall) for matrix distrib.   =        0.500000        0.500629
     time (cpu & wall) for numeric factor    =        9.296875        9.316100
     computational rate (gflops) for factor  =       53.317173       53.207145
     time (cpu & wall) for numeric solve     =        0.093750        0.099243
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        328724.        3. MB
                95-   1        393216.        3. MB        372309.        3. MB
                95-   2        327680.        2. MB        324793.        2. MB
                95-   3        360448.        3. MB        354203.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1380029.       11. MB


  Solver Memory allocated on core    0       =      680.288 MB
  Solver Memory allocated on core    1       =      689.503 MB
  Solver Memory allocated on core    2       =      680.207 MB
  Solver Memory allocated on core    3       =      649.872 MB
  Total Solver Memory allocated by all cores =     2699.870 MB





  Performance statistics for DSP solver: icalls =     37

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13042912
     no. of nonzeroes in the factor l        =       206637577
     ratio of nonzeroes in factor (min/max)  =          0.9577
     number of super nodes                   =            2845
     maximum order of a front matrix         =            6204
     maximum size of a front matrix          =        19247910
     maximum size of a front trapezoid       =        13909632
     no. of floating point ops for factor    =      4.9568D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8282
     ratio of allocated memory (max/min)     =          1.0610
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.046875        0.075094
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.250000        0.246576
     time (cpu & wall) for matrix distrib.   =        0.484375        0.474357
     time (cpu & wall) for numeric factor    =        9.234375        9.255050
     computational rate (gflops) for factor  =       53.678034       53.558124
     time (cpu & wall) for numeric solve     =        0.109375        0.096031
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        328724.        3. MB
                95-   1        393216.        3. MB        372309.        3. MB
                95-   2        327680.        2. MB        324793.        2. MB
                95-   3        360448.        3. MB        354203.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1441792.       11. MB       1380029.       11. MB


  Solver Memory allocated on core    0       =      680.288 MB
  Solver Memory allocated on core    1       =      689.492 MB
  Solver Memory allocated on core    2       =      680.207 MB
  Solver Memory allocated on core    3       =      649.872 MB
  Total Solver Memory allocated by all cores =     2699.860 MB





  Performance statistics for DSP solver: icalls =     38

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041904
     no. of nonzeroes in the factor l        =       211696107
     ratio of nonzeroes in factor (min/max)  =          0.8093
     number of super nodes                   =            2743
     maximum order of a front matrix         =            6798
     maximum size of a front matrix          =        23109801
     maximum size of a front trapezoid       =        17104956
     no. of floating point ops for factor    =      5.4173D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5898
     ratio of allocated memory (max/min)     =          1.2839
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.078125        0.086892
     time (cpu & wall) for ordering          =        0.734375        0.738621
     time (cpu & wall) for other matrix prep =        0.109375        0.105373
     time (cpu & wall) for value input       =        0.234375        0.236114
     time (cpu & wall) for matrix distrib.   =        0.468750        0.475004
     time (cpu & wall) for numeric factor    =       11.140625       11.128437
     computational rate (gflops) for factor  =       48.626170       48.679427
     time (cpu & wall) for numeric solve     =        0.093750        0.096947
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        347305.        3. MB
                95-   1        360448.        3. MB        347929.        3. MB
                95-   2        360448.        3. MB        341855.        3. MB
                95-   3        327680.        2. MB        325722.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1362811.       10. MB


  Solver Memory allocated on core    0       =      780.075 MB
  Solver Memory allocated on core    1       =      642.278 MB
  Solver Memory allocated on core    2       =      767.202 MB
  Solver Memory allocated on core    3       =      607.597 MB
  Total Solver Memory allocated by all cores =     2797.151 MB





  Performance statistics for DSP solver: icalls =     39

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041904
     no. of nonzeroes in the factor l        =       211696107
     ratio of nonzeroes in factor (min/max)  =          0.8093
     number of super nodes                   =            2743
     maximum order of a front matrix         =            6798
     maximum size of a front matrix          =        23109801
     maximum size of a front trapezoid       =        17104956
     no. of floating point ops for factor    =      5.4173D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5898
     ratio of allocated memory (max/min)     =          1.2839
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.265625        0.276634
     time (cpu & wall) for matrix distrib.   =        0.515625        0.518457
     time (cpu & wall) for numeric factor    =       11.187500       11.226563
     computational rate (gflops) for factor  =       48.422429       48.253943
     time (cpu & wall) for numeric solve     =        0.093750        0.097835
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        347305.        3. MB
                95-   1        360448.        3. MB        347929.        3. MB
                95-   2        360448.        3. MB        341855.        3. MB
                95-   3        327680.        2. MB        325722.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1362811.       10. MB


  Solver Memory allocated on core    0       =      780.075 MB
  Solver Memory allocated on core    1       =      642.278 MB
  Solver Memory allocated on core    2       =      767.202 MB
  Solver Memory allocated on core    3       =      607.597 MB
  Total Solver Memory allocated by all cores =     2797.151 MB





  Performance statistics for DSP solver: icalls =     40

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041904
     no. of nonzeroes in the factor l        =       211696107
     ratio of nonzeroes in factor (min/max)  =          0.8093
     number of super nodes                   =            2743
     maximum order of a front matrix         =            6798
     maximum size of a front matrix          =        23109801
     maximum size of a front trapezoid       =        17104956
     no. of floating point ops for factor    =      5.4173D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5898
     ratio of allocated memory (max/min)     =          1.2839
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.099119
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.250000        0.251390
     time (cpu & wall) for matrix distrib.   =        0.484375        0.487276
     time (cpu & wall) for numeric factor    =       11.046875       11.040584
     computational rate (gflops) for factor  =       49.038839       49.066783
     time (cpu & wall) for numeric solve     =        0.093750        0.098544
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        347305.        3. MB
                95-   1        360448.        3. MB        347929.        3. MB
                95-   2        360448.        3. MB        341855.        3. MB
                95-   3        327680.        2. MB        325722.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1362811.       10. MB


  Solver Memory allocated on core    0       =      780.075 MB
  Solver Memory allocated on core    1       =      642.277 MB
  Solver Memory allocated on core    2       =      767.202 MB
  Solver Memory allocated on core    3       =      607.597 MB
  Total Solver Memory allocated by all cores =     2797.151 MB





  Performance statistics for DSP solver: icalls =     41

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041904
     no. of nonzeroes in the factor l        =       211696107
     ratio of nonzeroes in factor (min/max)  =          0.8093
     number of super nodes                   =            2743
     maximum order of a front matrix         =            6798
     maximum size of a front matrix          =        23109801
     maximum size of a front trapezoid       =        17104956
     no. of floating point ops for factor    =      5.4173D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5898
     ratio of allocated memory (max/min)     =          1.2839
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.078125        0.084269
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.250000        0.248739
     time (cpu & wall) for matrix distrib.   =        0.500000        0.507862
     time (cpu & wall) for numeric factor    =       11.046875       11.035994
     computational rate (gflops) for factor  =       49.038839       49.087188
     time (cpu & wall) for numeric solve     =        0.109375        0.102548
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        347305.        3. MB
                95-   1        360448.        3. MB        347929.        3. MB
                95-   2        360448.        3. MB        341855.        3. MB
                95-   3        327680.        2. MB        325722.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1362811.       10. MB


  Solver Memory allocated on core    0       =      780.075 MB
  Solver Memory allocated on core    1       =      642.278 MB
  Solver Memory allocated on core    2       =      767.202 MB
  Solver Memory allocated on core    3       =      607.597 MB
  Total Solver Memory allocated by all cores =     2797.151 MB





  Performance statistics for DSP solver: icalls =     42

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041904
     no. of nonzeroes in the factor l        =       211696107
     ratio of nonzeroes in factor (min/max)  =          0.8093
     number of super nodes                   =            2743
     maximum order of a front matrix         =            6798
     maximum size of a front matrix          =        23109801
     maximum size of a front trapezoid       =        17104956
     no. of floating point ops for factor    =      5.4173D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5898
     ratio of allocated memory (max/min)     =          1.2839
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.265625        0.263308
     time (cpu & wall) for matrix distrib.   =        0.515625        0.504563
     time (cpu & wall) for numeric factor    =       11.171875       11.205554
     computational rate (gflops) for factor  =       48.490153       48.344414
     time (cpu & wall) for numeric solve     =        0.109375        0.097484
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        347305.        3. MB
                95-   1        360448.        3. MB        347929.        3. MB
                95-   2        360448.        3. MB        341855.        3. MB
                95-   3        327680.        2. MB        325722.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1362811.       10. MB


  Solver Memory allocated on core    0       =      780.075 MB
  Solver Memory allocated on core    1       =      642.278 MB
  Solver Memory allocated on core    2       =      767.202 MB
  Solver Memory allocated on core    3       =      607.597 MB
  Total Solver Memory allocated by all cores =     2797.151 MB





  Performance statistics for DSP solver: icalls =     43

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13041904
     no. of nonzeroes in the factor l        =       211696107
     ratio of nonzeroes in factor (min/max)  =          0.8093
     number of super nodes                   =            2743
     maximum order of a front matrix         =            6798
     maximum size of a front matrix          =        23109801
     maximum size of a front trapezoid       =        17104956
     no. of floating point ops for factor    =      5.4173D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5898
     ratio of allocated memory (max/min)     =          1.2839
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.078125        0.075100
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.265625        0.256187
     time (cpu & wall) for matrix distrib.   =        0.531250        0.526061
     time (cpu & wall) for numeric factor    =       11.296875       11.296100
     computational rate (gflops) for factor  =       47.953609       47.956898
     time (cpu & wall) for numeric solve     =        0.093750        0.102252
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        347305.        3. MB
                95-   1        360448.        3. MB        347929.        3. MB
                95-   2        360448.        3. MB        341855.        3. MB
                95-   3        327680.        2. MB        325722.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1362811.       10. MB


  Solver Memory allocated on core    0       =      780.075 MB
  Solver Memory allocated on core    1       =      642.277 MB
  Solver Memory allocated on core    2       =      767.202 MB
  Solver Memory allocated on core    3       =      607.597 MB
  Total Solver Memory allocated by all cores =     2797.151 MB





  Performance statistics for DSP solver: icalls =     44

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13040728
     no. of nonzeroes in the factor l        =       208904767
     ratio of nonzeroes in factor (min/max)  =          0.8350
     number of super nodes                   =            2789
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1793D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6089
     ratio of allocated memory (max/min)     =          1.1969
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.078125        0.086053
     time (cpu & wall) for ordering          =        0.734375        0.732258
     time (cpu & wall) for other matrix prep =        0.093750        0.105355
     time (cpu & wall) for value input       =        0.250000        0.257896
     time (cpu & wall) for matrix distrib.   =        0.500000        0.504216
     time (cpu & wall) for numeric factor    =       11.015625       11.016506
     computational rate (gflops) for factor  =       47.018147       47.014386
     time (cpu & wall) for numeric solve     =        0.109375        0.100747
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        340344.        3. MB
                95-   1        360448.        3. MB        353555.        3. MB
                95-   2        327680.        2. MB        322547.        2. MB
                95-   3        360448.        3. MB        353145.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369591.       10. MB


  Solver Memory allocated on core    0       =      761.930 MB
  Solver Memory allocated on core    1       =      636.593 MB
  Solver Memory allocated on core    2       =      686.760 MB
  Solver Memory allocated on core    3       =      660.205 MB
  Total Solver Memory allocated by all cores =     2745.489 MB





  Performance statistics for DSP solver: icalls =     45

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13040728
     no. of nonzeroes in the factor l        =       208904767
     ratio of nonzeroes in factor (min/max)  =          0.8350
     number of super nodes                   =            2789
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1793D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6089
     ratio of allocated memory (max/min)     =          1.1969
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.093587
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.236913
     time (cpu & wall) for matrix distrib.   =        0.515625        0.503573
     time (cpu & wall) for numeric factor    =       10.750000       10.780777
     computational rate (gflops) for factor  =       48.179932       48.042388
     time (cpu & wall) for numeric solve     =        0.093750        0.098212
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        340344.        3. MB
                95-   1        360448.        3. MB        353555.        3. MB
                95-   2        327680.        2. MB        322547.        2. MB
                95-   3        360448.        3. MB        353145.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369591.       10. MB


  Solver Memory allocated on core    0       =      761.930 MB
  Solver Memory allocated on core    1       =      636.589 MB
  Solver Memory allocated on core    2       =      686.760 MB
  Solver Memory allocated on core    3       =      660.205 MB
  Total Solver Memory allocated by all cores =     2745.484 MB





  Performance statistics for DSP solver: icalls =     46

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13040728
     no. of nonzeroes in the factor l        =       208904767
     ratio of nonzeroes in factor (min/max)  =          0.8350
     number of super nodes                   =            2789
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1793D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6089
     ratio of allocated memory (max/min)     =          1.1969
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.090270
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.281250        0.277631
     time (cpu & wall) for matrix distrib.   =        0.562500        0.561702
     time (cpu & wall) for numeric factor    =       10.718750       10.756892
     computational rate (gflops) for factor  =       48.320399       48.149062
     time (cpu & wall) for numeric solve     =        0.109375        0.110440
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        340344.        3. MB
                95-   1        360448.        3. MB        353555.        3. MB
                95-   2        327680.        2. MB        322547.        2. MB
                95-   3        360448.        3. MB        353145.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369591.       10. MB


  Solver Memory allocated on core    0       =      761.930 MB
  Solver Memory allocated on core    1       =      636.587 MB
  Solver Memory allocated on core    2       =      686.760 MB
  Solver Memory allocated on core    3       =      660.205 MB
  Total Solver Memory allocated by all cores =     2745.482 MB





  Performance statistics for DSP solver: icalls =     47

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13040728
     no. of nonzeroes in the factor l        =       208904767
     ratio of nonzeroes in factor (min/max)  =          0.8350
     number of super nodes                   =            2789
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1793D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6089
     ratio of allocated memory (max/min)     =          1.1969
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.078125        0.083491
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.265625        0.265576
     time (cpu & wall) for matrix distrib.   =        0.515625        0.518988
     time (cpu & wall) for numeric factor    =       10.687500       10.746812
     computational rate (gflops) for factor  =       48.461686       48.194225
     time (cpu & wall) for numeric solve     =        0.109375        0.099268
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        340344.        3. MB
                95-   1        360448.        3. MB        353555.        3. MB
                95-   2        327680.        2. MB        322547.        2. MB
                95-   3        360448.        3. MB        353145.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369591.       10. MB


  Solver Memory allocated on core    0       =      761.930 MB
  Solver Memory allocated on core    1       =      636.593 MB
  Solver Memory allocated on core    2       =      686.760 MB
  Solver Memory allocated on core    3       =      660.205 MB
  Total Solver Memory allocated by all cores =     2745.488 MB





  Performance statistics for DSP solver: icalls =     48

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13040728
     no. of nonzeroes in the factor l        =       208904767
     ratio of nonzeroes in factor (min/max)  =          0.8350
     number of super nodes                   =            2789
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1793D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6089
     ratio of allocated memory (max/min)     =          1.1969
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.250000        0.243323
     time (cpu & wall) for matrix distrib.   =        0.500000        0.495984
     time (cpu & wall) for numeric factor    =       10.437500       10.439826
     computational rate (gflops) for factor  =       49.622445       49.611389
     time (cpu & wall) for numeric solve     =        0.093750        0.097234
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        340344.        3. MB
                95-   1        360448.        3. MB        353555.        3. MB
                95-   2        327680.        2. MB        322547.        2. MB
                95-   3        360448.        3. MB        353145.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369591.       10. MB


  Solver Memory allocated on core    0       =      761.930 MB
  Solver Memory allocated on core    1       =      636.593 MB
  Solver Memory allocated on core    2       =      686.760 MB
  Solver Memory allocated on core    3       =      660.205 MB
  Total Solver Memory allocated by all cores =     2745.488 MB





  Performance statistics for DSP solver: icalls =     49

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13040728
     no. of nonzeroes in the factor l        =       208904767
     ratio of nonzeroes in factor (min/max)  =          0.8350
     number of super nodes                   =            2789
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1793D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6089
     ratio of allocated memory (max/min)     =          1.1969
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.096612
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.218750        0.218835
     time (cpu & wall) for matrix distrib.   =        0.562500        0.575487
     time (cpu & wall) for numeric factor    =       10.812500       10.801451
     computational rate (gflops) for factor  =       47.901436       47.950435
     time (cpu & wall) for numeric solve     =        0.109375        0.103464
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        340344.        3. MB
                95-   1        360448.        3. MB        353555.        3. MB
                95-   2        327680.        2. MB        322547.        2. MB
                95-   3        360448.        3. MB        353145.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369591.       10. MB


  Solver Memory allocated on core    0       =      761.930 MB
  Solver Memory allocated on core    1       =      636.585 MB
  Solver Memory allocated on core    2       =      686.760 MB
  Solver Memory allocated on core    3       =      660.205 MB
  Total Solver Memory allocated by all cores =     2745.480 MB





  Performance statistics for DSP solver: icalls =     50

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13040728
     no. of nonzeroes in the factor l        =       208904767
     ratio of nonzeroes in factor (min/max)  =          0.8350
     number of super nodes                   =            2789
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1793D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6089
     ratio of allocated memory (max/min)     =          1.1969
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.082645
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.250000        0.245462
     time (cpu & wall) for matrix distrib.   =        0.546875        0.546812
     time (cpu & wall) for numeric factor    =       10.796875       10.791551
     computational rate (gflops) for factor  =       47.970757       47.994424
     time (cpu & wall) for numeric solve     =        0.093750        0.100323
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        340344.        3. MB
                95-   1        360448.        3. MB        353555.        3. MB
                95-   2        327680.        2. MB        322547.        2. MB
                95-   3        360448.        3. MB        353145.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369591.       10. MB


  Solver Memory allocated on core    0       =      761.930 MB
  Solver Memory allocated on core    1       =      636.576 MB
  Solver Memory allocated on core    2       =      686.760 MB
  Solver Memory allocated on core    3       =      660.205 MB
  Total Solver Memory allocated by all cores =     2745.471 MB





  Performance statistics for DSP solver: icalls =     51

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13039072
     no. of nonzeroes in the factor l        =       207896375
     ratio of nonzeroes in factor (min/max)  =          0.8481
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1348D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6356
     ratio of allocated memory (max/min)     =          1.1798
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.085137
     time (cpu & wall) for ordering          =        0.703125        0.692459
     time (cpu & wall) for other matrix prep =        0.093750        0.090440
     time (cpu & wall) for value input       =        0.250000        0.251042
     time (cpu & wall) for matrix distrib.   =        0.546875        0.548973
     time (cpu & wall) for numeric factor    =       10.468750       10.481179
     computational rate (gflops) for factor  =       49.048679       48.990514
     time (cpu & wall) for numeric solve     =        0.109375        0.094758
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        344367.        3. MB
                95-   1        360448.        3. MB        349045.        3. MB
                95-   2        327680.        2. MB        324425.        2. MB
                95-   3        360448.        3. MB        352037.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369874.       10. MB


  Solver Memory allocated on core    0       =      754.362 MB
  Solver Memory allocated on core    1       =      639.411 MB
  Solver Memory allocated on core    2       =      692.147 MB
  Solver Memory allocated on core    3       =      651.090 MB
  Total Solver Memory allocated by all cores =     2737.010 MB





  Performance statistics for DSP solver: icalls =     52

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13039072
     no. of nonzeroes in the factor l        =       207896375
     ratio of nonzeroes in factor (min/max)  =          0.8481
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1348D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6356
     ratio of allocated memory (max/min)     =          1.1798
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.092342
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.230906
     time (cpu & wall) for matrix distrib.   =        0.500000        0.496740
     time (cpu & wall) for numeric factor    =       10.546875       10.584687
     computational rate (gflops) for factor  =       48.685356       48.511436
     time (cpu & wall) for numeric solve     =        0.093750        0.096208
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        344367.        3. MB
                95-   1        360448.        3. MB        349045.        3. MB
                95-   2        327680.        2. MB        324425.        2. MB
                95-   3        360448.        3. MB        352037.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369874.       10. MB


  Solver Memory allocated on core    0       =      754.362 MB
  Solver Memory allocated on core    1       =      639.403 MB
  Solver Memory allocated on core    2       =      692.147 MB
  Solver Memory allocated on core    3       =      651.090 MB
  Total Solver Memory allocated by all cores =     2737.001 MB





  Performance statistics for DSP solver: icalls =     53

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13039072
     no. of nonzeroes in the factor l        =       207896375
     ratio of nonzeroes in factor (min/max)  =          0.8481
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1348D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6356
     ratio of allocated memory (max/min)     =          1.1798
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.078125        0.078030
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.220077
     time (cpu & wall) for matrix distrib.   =        0.562500        0.580354
     time (cpu & wall) for numeric factor    =       10.812500       10.807295
     computational rate (gflops) for factor  =       47.489328       47.512201
     time (cpu & wall) for numeric solve     =        0.109375        0.105460
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        344367.        3. MB
                95-   1        360448.        3. MB        349045.        3. MB
                95-   2        327680.        2. MB        324425.        2. MB
                95-   3        360448.        3. MB        352037.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369874.       10. MB


  Solver Memory allocated on core    0       =      754.362 MB
  Solver Memory allocated on core    1       =      639.382 MB
  Solver Memory allocated on core    2       =      692.147 MB
  Solver Memory allocated on core    3       =      651.090 MB
  Total Solver Memory allocated by all cores =     2736.981 MB





  Performance statistics for DSP solver: icalls =     54

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13039072
     no. of nonzeroes in the factor l        =       207896375
     ratio of nonzeroes in factor (min/max)  =          0.8481
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1348D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6356
     ratio of allocated memory (max/min)     =          1.1798
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.239949
     time (cpu & wall) for matrix distrib.   =        0.500000        0.502503
     time (cpu & wall) for numeric factor    =       10.546875       10.556929
     computational rate (gflops) for factor  =       48.685356       48.638991
     time (cpu & wall) for numeric solve     =        0.093750        0.095320
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        344367.        3. MB
                95-   1        360448.        3. MB        349045.        3. MB
                95-   2        327680.        2. MB        324425.        2. MB
                95-   3        360448.        3. MB        352037.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369874.       10. MB


  Solver Memory allocated on core    0       =      754.362 MB
  Solver Memory allocated on core    1       =      639.382 MB
  Solver Memory allocated on core    2       =      692.147 MB
  Solver Memory allocated on core    3       =      651.090 MB
  Total Solver Memory allocated by all cores =     2736.981 MB





  Performance statistics for DSP solver: icalls =     55

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13039072
     no. of nonzeroes in the factor l        =       207896375
     ratio of nonzeroes in factor (min/max)  =          0.8481
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1348D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6356
     ratio of allocated memory (max/min)     =          1.1798
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.231076
     time (cpu & wall) for matrix distrib.   =        0.500000        0.502011
     time (cpu & wall) for numeric factor    =       10.562500       10.613902
     computational rate (gflops) for factor  =       48.613336       48.377905
     time (cpu & wall) for numeric solve     =        0.109375        0.104594
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        344367.        3. MB
                95-   1        360448.        3. MB        349045.        3. MB
                95-   2        327680.        2. MB        324425.        2. MB
                95-   3        360448.        3. MB        352037.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369874.       10. MB


  Solver Memory allocated on core    0       =      754.362 MB
  Solver Memory allocated on core    1       =      639.382 MB
  Solver Memory allocated on core    2       =      692.147 MB
  Solver Memory allocated on core    3       =      651.090 MB
  Total Solver Memory allocated by all cores =     2736.981 MB





  Performance statistics for DSP solver: icalls =     56

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13039072
     no. of nonzeroes in the factor l        =       207896375
     ratio of nonzeroes in factor (min/max)  =          0.8481
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1348D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6356
     ratio of allocated memory (max/min)     =          1.1805
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.078125        0.079291
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.296875        0.285220
     time (cpu & wall) for matrix distrib.   =        0.515625        0.512079
     time (cpu & wall) for numeric factor    =       10.453125       10.448154
     computational rate (gflops) for factor  =       49.121996       49.145366
     time (cpu & wall) for numeric solve     =        0.093750        0.093392
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        344367.        3. MB
                95-   1        360448.        3. MB        349045.        3. MB
                95-   2        327680.        2. MB        324425.        2. MB
                95-   3        360448.        3. MB        352037.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369874.       10. MB


  Solver Memory allocated on core    0       =      754.362 MB
  Solver Memory allocated on core    1       =      639.025 MB
  Solver Memory allocated on core    2       =      692.147 MB
  Solver Memory allocated on core    3       =      651.090 MB
  Total Solver Memory allocated by all cores =     2736.624 MB





  Performance statistics for DSP solver: icalls =     57

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13039072
     no. of nonzeroes in the factor l        =       207896375
     ratio of nonzeroes in factor (min/max)  =          0.8481
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1348D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6356
     ratio of allocated memory (max/min)     =          1.1805
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.237602
     time (cpu & wall) for matrix distrib.   =        0.531250        0.527736
     time (cpu & wall) for numeric factor    =       10.328125       10.355573
     computational rate (gflops) for factor  =       49.716513       49.584739
     time (cpu & wall) for numeric solve     =        0.093750        0.100710
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        344367.        3. MB
                95-   1        360448.        3. MB        349045.        3. MB
                95-   2        327680.        2. MB        324425.        2. MB
                95-   3        360448.        3. MB        352037.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369874.       10. MB


  Solver Memory allocated on core    0       =      754.362 MB
  Solver Memory allocated on core    1       =      639.025 MB
  Solver Memory allocated on core    2       =      692.147 MB
  Solver Memory allocated on core    3       =      651.090 MB
  Total Solver Memory allocated by all cores =     2736.624 MB





  Performance statistics for DSP solver: icalls =     58

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          161520
     no. of nonzeroes in lower triangle of a =        13039072
     no. of nonzeroes in the factor l        =       207896375
     ratio of nonzeroes in factor (min/max)  =          0.8481
     number of super nodes                   =            2792
     maximum order of a front matrix         =            6699
     maximum size of a front matrix          =        22441650
     maximum size of a front trapezoid       =        16436805
     no. of floating point ops for factor    =      5.1348D+11
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6356
     ratio of allocated memory (max/min)     =          1.1805
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.232382
     time (cpu & wall) for matrix distrib.   =        0.562500        0.552470
     time (cpu & wall) for numeric factor    =       10.406250       10.458684
     computational rate (gflops) for factor  =       49.343266       49.095887
     time (cpu & wall) for numeric solve     =        0.093750        0.099791
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        344367.        3. MB
                95-   1        360448.        3. MB        349045.        3. MB
                95-   2        327680.        2. MB        324425.        2. MB
                95-   3        360448.        3. MB        352037.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1369874.       10. MB


  Solver Memory allocated on core    0       =      754.362 MB
  Solver Memory allocated on core    1       =      639.025 MB
  Solver Memory allocated on core    2       =      692.147 MB
  Solver Memory allocated on core    3       =      651.090 MB
  Total Solver Memory allocated by all cores =     2736.624 MB

