function importfile('C:\Users\Jam\Desktop\temp\MatlabCodes\area4-1.txt')
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 26-Oct-2012 16:10:23

DELIMITER = ' ';
HEADERLINES = 190;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end
 
